---@meta

---@alias BGEvents
---| 1 # BG_EVENT_ON_START
---| 2 # BG_EVENT_ON_END
---| 3 # BG_EVENT_ON_CREATE
---| 4 # BG_EVENT_ON_PRE_DESTROY
---| 5 # BG_EVENT_COUNT

-- BGEvents
BG_EVENT_ON_START = 1
BG_EVENT_ON_END = 2
BG_EVENT_ON_CREATE = 3
BG_EVENT_ON_PRE_DESTROY = 4
BG_EVENT_COUNT = 5

---@alias BanMode
---| 0 # BAN_ACCOUNT
---| 1 # BAN_CHARACTER
---| 2 # BAN_IP

-- BanMode
BAN_ACCOUNT = 0
BAN_CHARACTER = 1
BAN_IP = 2

---@alias CorpseType
---| 0 # CORPSE_BONES
---| 1 # CORPSE_RESURRECTABLE_PVE
---| 2 # CORPSE_RESURRECTABLE_PVP

-- CorpseType
CORPSE_BONES = 0
CORPSE_RESURRECTABLE_PVE = 1
CORPSE_RESURRECTABLE_PVP = 2

---@alias CreatureEvents
---| 1 # CREATURE_EVENT_ON_ENTER_COMBAT
---| 2 # CREATURE_EVENT_ON_LEAVE_COMBAT
---| 3 # CREATURE_EVENT_ON_TARGET_DIED
---| 4 # CREATURE_EVENT_ON_DIED
---| 5 # CREATURE_EVENT_ON_SPAWN
---| 6 # CREATURE_EVENT_ON_REACH_WP
---| 7 # CREATURE_EVENT_ON_AIUPDATE
---| 8 # CREATURE_EVENT_ON_RECEIVE_EMOTE
---| 9 # CREATURE_EVENT_ON_DAMAGE_TAKEN
---| 10 # CREATURE_EVENT_ON_PRE_COMBAT
---| 12 # CREATURE_EVENT_ON_OWNER_ATTACKED
---| 13 # CREATURE_EVENT_ON_OWNER_ATTACKED_AT
---| 14 # CREATURE_EVENT_ON_HIT_BY_SPELL
---| 15 # CREATURE_EVENT_ON_SPELL_HIT_TARGET
---| 19 # CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE
---| 20 # CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN
---| 21 # CREATURE_EVENT_ON_SUMMONED_CREATURE_DIED
---| 22 # CREATURE_EVENT_ON_SUMMONED
---| 23 # CREATURE_EVENT_ON_RESET
---| 24 # CREATURE_EVENT_ON_REACH_HOME
---| 26 # CREATURE_EVENT_ON_CORPSE_REMOVED
---| 27 # CREATURE_EVENT_ON_MOVE_IN_LOS
---| 30 # CREATURE_EVENT_ON_DUMMY_EFFECT
---| 31 # CREATURE_EVENT_ON_QUEST_ACCEPT
---| 34 # CREATURE_EVENT_ON_QUEST_REWARD
---| 35 # CREATURE_EVENT_ON_DIALOG_STATUS
---| 36 # CREATURE_EVENT_ON_ADD
---| 37 # CREATURE_EVENT_ON_REMOVE
---| 38 # CREATURE_EVENT_COUNT

-- CreatureEvents
CREATURE_EVENT_ON_ENTER_COMBAT = 1
CREATURE_EVENT_ON_LEAVE_COMBAT = 2
CREATURE_EVENT_ON_TARGET_DIED = 3
CREATURE_EVENT_ON_DIED = 4
CREATURE_EVENT_ON_SPAWN = 5
CREATURE_EVENT_ON_REACH_WP = 6
CREATURE_EVENT_ON_AIUPDATE = 7
CREATURE_EVENT_ON_RECEIVE_EMOTE = 8
CREATURE_EVENT_ON_DAMAGE_TAKEN = 9
CREATURE_EVENT_ON_PRE_COMBAT = 10
CREATURE_EVENT_ON_OWNER_ATTACKED = 12
CREATURE_EVENT_ON_OWNER_ATTACKED_AT = 13
CREATURE_EVENT_ON_HIT_BY_SPELL = 14
CREATURE_EVENT_ON_SPELL_HIT_TARGET = 15
CREATURE_EVENT_ON_JUST_SUMMONED_CREATURE = 19
CREATURE_EVENT_ON_SUMMONED_CREATURE_DESPAWN = 20
CREATURE_EVENT_ON_SUMMONED_CREATURE_DIED = 21
CREATURE_EVENT_ON_SUMMONED = 22
CREATURE_EVENT_ON_RESET = 23
CREATURE_EVENT_ON_REACH_HOME = 24
CREATURE_EVENT_ON_CORPSE_REMOVED = 26
CREATURE_EVENT_ON_MOVE_IN_LOS = 27
CREATURE_EVENT_ON_DUMMY_EFFECT = 30
CREATURE_EVENT_ON_QUEST_ACCEPT = 31
CREATURE_EVENT_ON_QUEST_REWARD = 34
CREATURE_EVENT_ON_DIALOG_STATUS = 35
CREATURE_EVENT_ON_ADD = 36
CREATURE_EVENT_ON_REMOVE = 37
CREATURE_EVENT_COUNT = 38

---@alias CreatureFamily
---| 0 # CREATURE_FAMILY_NONE
---| 1 # CREATURE_FAMILY_WOLF
---| 2 # CREATURE_FAMILY_CAT
---| 3 # CREATURE_FAMILY_SPIDER
---| 4 # CREATURE_FAMILY_BEAR
---| 5 # CREATURE_FAMILY_BOAR
---| 6 # CREATURE_FAMILY_CROCOLISK
---| 7 # CREATURE_FAMILY_CARRION_BIRD
---| 8 # CREATURE_FAMILY_CRAB
---| 9 # CREATURE_FAMILY_GORILLA
---| 10 # CREATURE_FAMILY_HORSE_CUSTOM
---| 11 # CREATURE_FAMILY_RAPTOR
---| 12 # CREATURE_FAMILY_TALLSTRIDER
---| 15 # CREATURE_FAMILY_FELHUNTER
---| 16 # CREATURE_FAMILY_VOIDWALKER
---| 17 # CREATURE_FAMILY_SUCCUBUS
---| 19 # CREATURE_FAMILY_DOOMGUARD
---| 20 # CREATURE_FAMILY_SCORPID
---| 21 # CREATURE_FAMILY_TURTLE
---| 23 # CREATURE_FAMILY_IMP
---| 24 # CREATURE_FAMILY_BAT
---| 25 # CREATURE_FAMILY_HYENA
---| 26 # CREATURE_FAMILY_BIRD_OF_PREY
---| 27 # CREATURE_FAMILY_WIND_SERPENT
---| 28 # CREATURE_FAMILY_REMOTE_CONTROL
---| 29 # CREATURE_FAMILY_FELGUARD
---| 30 # CREATURE_FAMILY_DRAGONHAWK
---| 31 # CREATURE_FAMILY_RAVAGER
---| 32 # CREATURE_FAMILY_WARP_STALKER
---| 33 # CREATURE_FAMILY_SPOREBAT
---| 34 # CREATURE_FAMILY_NETHER_RAY
---| 35 # CREATURE_FAMILY_SERPENT
---| 36 # CREATURE_FAMILY_SEA_LION
---| 37 # CREATURE_FAMILY_MOTH
---| 38 # CREATURE_FAMILY_CHIMAERA
---| 39 # CREATURE_FAMILY_DEVILSAUR
---| 40 # CREATURE_FAMILY_GHOUL
---| 41 # CREATURE_FAMILY_SILITHID
---| 42 # CREATURE_FAMILY_WORM
---| 43 # CREATURE_FAMILY_RHINO
---| 44 # CREATURE_FAMILY_WASP
---| 45 # CREATURE_FAMILY_CORE_HOUND
---| 46 # CREATURE_FAMILY_SPIRIT_BEAST

-- CreatureFamily
CREATURE_FAMILY_NONE = 0
CREATURE_FAMILY_WOLF = 1
CREATURE_FAMILY_CAT = 2
CREATURE_FAMILY_SPIDER = 3
CREATURE_FAMILY_BEAR = 4
CREATURE_FAMILY_BOAR = 5
CREATURE_FAMILY_CROCOLISK = 6
CREATURE_FAMILY_CARRION_BIRD = 7
CREATURE_FAMILY_CRAB = 8
CREATURE_FAMILY_GORILLA = 9
CREATURE_FAMILY_HORSE_CUSTOM = 10
CREATURE_FAMILY_RAPTOR = 11
CREATURE_FAMILY_TALLSTRIDER = 12
CREATURE_FAMILY_FELHUNTER = 15
CREATURE_FAMILY_VOIDWALKER = 16
CREATURE_FAMILY_SUCCUBUS = 17
CREATURE_FAMILY_DOOMGUARD = 19
CREATURE_FAMILY_SCORPID = 20
CREATURE_FAMILY_TURTLE = 21
CREATURE_FAMILY_IMP = 23
CREATURE_FAMILY_BAT = 24
CREATURE_FAMILY_HYENA = 25
CREATURE_FAMILY_BIRD_OF_PREY = 26
CREATURE_FAMILY_WIND_SERPENT = 27
CREATURE_FAMILY_REMOTE_CONTROL = 28
CREATURE_FAMILY_FELGUARD = 29
CREATURE_FAMILY_DRAGONHAWK = 30
CREATURE_FAMILY_RAVAGER = 31
CREATURE_FAMILY_WARP_STALKER = 32
CREATURE_FAMILY_SPOREBAT = 33
CREATURE_FAMILY_NETHER_RAY = 34
CREATURE_FAMILY_SERPENT = 35
CREATURE_FAMILY_SEA_LION = 36
CREATURE_FAMILY_MOTH = 37
CREATURE_FAMILY_CHIMAERA = 38
CREATURE_FAMILY_DEVILSAUR = 39
CREATURE_FAMILY_GHOUL = 40
CREATURE_FAMILY_SILITHID = 41
CREATURE_FAMILY_WORM = 42
CREATURE_FAMILY_RHINO = 43
CREATURE_FAMILY_WASP = 44
CREATURE_FAMILY_CORE_HOUND = 45
CREATURE_FAMILY_SPIRIT_BEAST = 46

---@alias CreatureType
---| 1 # CREATURE_TYPE_BEAST
---| 2 # CREATURE_TYPE_DRAGONKIN
---| 3 # CREATURE_TYPE_DEMON
---| 4 # CREATURE_TYPE_ELEMENTAL
---| 5 # CREATURE_TYPE_GIANT
---| 6 # CREATURE_TYPE_UNDEAD
---| 7 # CREATURE_TYPE_HUMANOID
---| 8 # CREATURE_TYPE_CRITTER
---| 9 # CREATURE_TYPE_MECHANICAL
---| 10 # CREATURE_TYPE_NOT_SPECIFIED
---| 11 # CREATURE_TYPE_TOTEM
---| 12 # CREATURE_TYPE_NON_COMBAT_PET
---| 13 # CREATURE_TYPE_GAS_CLOUD

-- CreatureType
CREATURE_TYPE_BEAST = 1
CREATURE_TYPE_DRAGONKIN = 2
CREATURE_TYPE_DEMON = 3
CREATURE_TYPE_ELEMENTAL = 4
CREATURE_TYPE_GIANT = 5
CREATURE_TYPE_UNDEAD = 6
CREATURE_TYPE_HUMANOID = 7
CREATURE_TYPE_CRITTER = 8
CREATURE_TYPE_MECHANICAL = 9
CREATURE_TYPE_NOT_SPECIFIED = 10
CREATURE_TYPE_TOTEM = 11
CREATURE_TYPE_NON_COMBAT_PET = 12
CREATURE_TYPE_GAS_CLOUD = 13

---@alias CurrentSpellTypes
---| 0 # CURRENT_MELEE_SPELL
---| 1 # CURRENT_GENERIC_SPELL
---| 2 # CURRENT_CHANNELED_SPELL
---| 3 # CURRENT_AUTOREPEAT_SPELL

-- CurrentSpellTypes
CURRENT_MELEE_SPELL = 0
CURRENT_GENERIC_SPELL = 1
CURRENT_CHANNELED_SPELL = 2
CURRENT_AUTOREPEAT_SPELL = 3

---@alias GOState
---| 0 # GO_STATE_ACTIVE
---| 1 # GO_STATE_READY
---| 2 # GO_STATE_ACTIVE_ALTERNATIVE

-- GOState
GO_STATE_ACTIVE = 0
GO_STATE_READY = 1
GO_STATE_ACTIVE_ALTERNATIVE = 2

---@alias GameObjectEvents
---| 1 # GAMEOBJECT_EVENT_ON_AIUPDATE
---| 2 # GAMEOBJECT_EVENT_ON_SPAWN
---| 3 # GAMEOBJECT_EVENT_ON_DUMMY_EFFECT
---| 4 # GAMEOBJECT_EVENT_ON_QUEST_ACCEPT
---| 5 # GAMEOBJECT_EVENT_ON_QUEST_REWARD
---| 6 # GAMEOBJECT_EVENT_ON_DIALOG_STATUS
---| 7 # GAMEOBJECT_EVENT_ON_DESTROYED
---| 8 # GAMEOBJECT_EVENT_ON_DAMAGED
---| 9 # GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE
---| 10 # GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED
---| 12 # GAMEOBJECT_EVENT_ON_ADD
---| 13 # GAMEOBJECT_EVENT_ON_REMOVE
---| 14 # GAMEOBJECT_EVENT_ON_USE
---| 15 # GAMEOBJECT_EVENT_COUNT

-- GameObjectEvents
GAMEOBJECT_EVENT_ON_AIUPDATE = 1
GAMEOBJECT_EVENT_ON_SPAWN = 2
GAMEOBJECT_EVENT_ON_DUMMY_EFFECT = 3
GAMEOBJECT_EVENT_ON_QUEST_ACCEPT = 4
GAMEOBJECT_EVENT_ON_QUEST_REWARD = 5
GAMEOBJECT_EVENT_ON_DIALOG_STATUS = 6
GAMEOBJECT_EVENT_ON_DESTROYED = 7
GAMEOBJECT_EVENT_ON_DAMAGED = 8
GAMEOBJECT_EVENT_ON_LOOT_STATE_CHANGE = 9
GAMEOBJECT_EVENT_ON_GO_STATE_CHANGED = 10
GAMEOBJECT_EVENT_ON_ADD = 12
GAMEOBJECT_EVENT_ON_REMOVE = 13
GAMEOBJECT_EVENT_ON_USE = 14
GAMEOBJECT_EVENT_COUNT = 15

---@alias GossipEvents
---| 1 # GOSSIP_EVENT_ON_HELLO
---| 2 # GOSSIP_EVENT_ON_SELECT
---| 3 # GOSSIP_EVENT_COUNT

-- GossipEvents
GOSSIP_EVENT_ON_HELLO = 1
GOSSIP_EVENT_ON_SELECT = 2
GOSSIP_EVENT_COUNT = 3

---@alias GroupEvents
---| 1 # GROUP_EVENT_ON_MEMBER_ADD
---| 2 # GROUP_EVENT_ON_MEMBER_INVITE
---| 3 # GROUP_EVENT_ON_MEMBER_REMOVE
---| 4 # GROUP_EVENT_ON_LEADER_CHANGE
---| 5 # GROUP_EVENT_ON_DISBAND
---| 6 # GROUP_EVENT_ON_CREATE
---| 7 # GROUP_EVENT_COUNT

-- GroupEvents
GROUP_EVENT_ON_MEMBER_ADD = 1
GROUP_EVENT_ON_MEMBER_INVITE = 2
GROUP_EVENT_ON_MEMBER_REMOVE = 3
GROUP_EVENT_ON_LEADER_CHANGE = 4
GROUP_EVENT_ON_DISBAND = 5
GROUP_EVENT_ON_CREATE = 6
GROUP_EVENT_COUNT = 7

---@alias GroupMemberFlags
---| 1 # MEMBER_FLAG_ASSISTANT
---| 2 # MEMBER_FLAG_MAINTANK
---| 4 # MEMBER_FLAG_MAINASSIST

-- GroupMemberFlags
MEMBER_FLAG_ASSISTANT = 1
MEMBER_FLAG_MAINTANK = 2
MEMBER_FLAG_MAINASSIST = 4

---@alias GroupType
---| 0 # GROUPTYPE_NORMAL
---| 1 # GROUPTYPE_BG
---| 2 # GROUPTYPE_RAID
---| 4 # GROUPTYPE_LFG_RESTRICTED
---| 8 # GROUPTYPE_LFG

-- GroupType
GROUPTYPE_NORMAL = 0
GROUPTYPE_BG = 1
GROUPTYPE_RAID = 2
GROUPTYPE_LFG_RESTRICTED = 4
GROUPTYPE_LFG = 8

---@alias GuildEvents
---| 1 # GUILD_EVENT_ON_ADD_MEMBER
---| 2 # GUILD_EVENT_ON_REMOVE_MEMBER
---| 3 # GUILD_EVENT_ON_MOTD_CHANGE
---| 4 # GUILD_EVENT_ON_INFO_CHANGE
---| 5 # GUILD_EVENT_ON_CREATE
---| 6 # GUILD_EVENT_ON_DISBAND
---| 7 # GUILD_EVENT_ON_MONEY_WITHDRAW
---| 8 # GUILD_EVENT_ON_MONEY_DEPOSIT
---| 9 # GUILD_EVENT_ON_ITEM_MOVE
---| 10 # GUILD_EVENT_ON_EVENT
---| 11 # GUILD_EVENT_ON_BANK_EVENT
---| 12 # GUILD_EVENT_COUNT

-- GuildEvents
GUILD_EVENT_ON_ADD_MEMBER = 1
GUILD_EVENT_ON_REMOVE_MEMBER = 2
GUILD_EVENT_ON_MOTD_CHANGE = 3
GUILD_EVENT_ON_INFO_CHANGE = 4
GUILD_EVENT_ON_CREATE = 5
GUILD_EVENT_ON_DISBAND = 6
GUILD_EVENT_ON_MONEY_WITHDRAW = 7
GUILD_EVENT_ON_MONEY_DEPOSIT = 8
GUILD_EVENT_ON_ITEM_MOVE = 9
GUILD_EVENT_ON_EVENT = 10
GUILD_EVENT_ON_BANK_EVENT = 11
GUILD_EVENT_COUNT = 12

---@alias InstanceEvents
---| 1 # INSTANCE_EVENT_ON_INITIALIZE
---| 2 # INSTANCE_EVENT_ON_LOAD
---| 3 # INSTANCE_EVENT_ON_UPDATE
---| 4 # INSTANCE_EVENT_ON_PLAYER_ENTER
---| 5 # INSTANCE_EVENT_ON_CREATURE_CREATE
---| 6 # INSTANCE_EVENT_ON_GAMEOBJECT_CREATE
---| 7 # INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS
---| 8 # INSTANCE_EVENT_COUNT

-- InstanceEvents
INSTANCE_EVENT_ON_INITIALIZE = 1
INSTANCE_EVENT_ON_LOAD = 2
INSTANCE_EVENT_ON_UPDATE = 3
INSTANCE_EVENT_ON_PLAYER_ENTER = 4
INSTANCE_EVENT_ON_CREATURE_CREATE = 5
INSTANCE_EVENT_ON_GAMEOBJECT_CREATE = 6
INSTANCE_EVENT_ON_CHECK_ENCOUNTER_IN_PROGRESS = 7
INSTANCE_EVENT_COUNT = 8

---@alias InventorySlots
---| 0 # EQUIPMENT_SLOT_START
---| 0 # EQUIPMENT_SLOT_HEAD
---| 1 # EQUIPMENT_SLOT_NECK
---| 2 # EQUIPMENT_SLOT_SHOULDERS
---| 3 # EQUIPMENT_SLOT_BODY
---| 4 # EQUIPMENT_SLOT_CHEST
---| 5 # EQUIPMENT_SLOT_WAIST
---| 6 # EQUIPMENT_SLOT_LEGS
---| 7 # EQUIPMENT_SLOT_FEET
---| 8 # EQUIPMENT_SLOT_WRISTS
---| 9 # EQUIPMENT_SLOT_HANDS
---| 10 # EQUIPMENT_SLOT_FINGER1
---| 11 # EQUIPMENT_SLOT_FINGER2
---| 12 # EQUIPMENT_SLOT_TRINKET1
---| 13 # EQUIPMENT_SLOT_TRINKET2
---| 14 # EQUIPMENT_SLOT_BACK
---| 15 # EQUIPMENT_SLOT_MAINHAND
---| 16 # EQUIPMENT_SLOT_OFFHAND
---| 17 # EQUIPMENT_SLOT_RANGED
---| 18 # EQUIPMENT_SLOT_TABARD
---| 19 # INVENTORY_SLOT_BAG_START
---| 19 # EQUIPMENT_SLOT_END
---| 23 # INVENTORY_SLOT_BAG_END

-- InventorySlots
EQUIPMENT_SLOT_START = 0
EQUIPMENT_SLOT_HEAD = 0
EQUIPMENT_SLOT_NECK = 1
EQUIPMENT_SLOT_SHOULDERS = 2
EQUIPMENT_SLOT_BODY = 3
EQUIPMENT_SLOT_CHEST = 4
EQUIPMENT_SLOT_WAIST = 5
EQUIPMENT_SLOT_LEGS = 6
EQUIPMENT_SLOT_FEET = 7
EQUIPMENT_SLOT_WRISTS = 8
EQUIPMENT_SLOT_HANDS = 9
EQUIPMENT_SLOT_FINGER1 = 10
EQUIPMENT_SLOT_FINGER2 = 11
EQUIPMENT_SLOT_TRINKET1 = 12
EQUIPMENT_SLOT_TRINKET2 = 13
EQUIPMENT_SLOT_BACK = 14
EQUIPMENT_SLOT_MAINHAND = 15
EQUIPMENT_SLOT_OFFHAND = 16
EQUIPMENT_SLOT_RANGED = 17
EQUIPMENT_SLOT_TABARD = 18
INVENTORY_SLOT_BAG_START = 19
EQUIPMENT_SLOT_END = 19
INVENTORY_SLOT_BAG_END = 23

---@alias ItemEvents
---| 1 # ITEM_EVENT_ON_DUMMY_EFFECT
---| 2 # ITEM_EVENT_ON_USE
---| 3 # ITEM_EVENT_ON_QUEST_ACCEPT
---| 4 # ITEM_EVENT_ON_EXPIRE
---| 5 # ITEM_EVENT_ON_REMOVE
---| 6 # ITEM_EVENT_COUNT

-- ItemEvents
ITEM_EVENT_ON_DUMMY_EFFECT = 1
ITEM_EVENT_ON_USE = 2
ITEM_EVENT_ON_QUEST_ACCEPT = 3
ITEM_EVENT_ON_EXPIRE = 4
ITEM_EVENT_ON_REMOVE = 5
ITEM_EVENT_COUNT = 6

---@alias LocaleConstant
---| 0 # LOCALE_enUS
---| 1 # LOCALE_koKR
---| 2 # LOCALE_frFR
---| 3 # LOCALE_deDE
---| 4 # LOCALE_zhCN
---| 5 # LOCALE_zhTW
---| 6 # LOCALE_esES
---| 7 # LOCALE_esMX
---| 8 # LOCALE_ruRU

-- LocaleConstant
LOCALE_enUS = 0
LOCALE_koKR = 1
LOCALE_frFR = 2
LOCALE_deDE = 3
LOCALE_zhCN = 4
LOCALE_zhTW = 5
LOCALE_esES = 6
LOCALE_esMX = 7
LOCALE_ruRU = 8

---@alias LootState
---| 0 # GO_NOT_READY
---| 1 # GO_READY
---| 2 # GO_ACTIVATED
---| 3 # GO_JUST_DEACTIVATED

-- LootState
GO_NOT_READY = 0
GO_READY = 1
GO_ACTIVATED = 2
GO_JUST_DEACTIVATED = 3

---@alias MailStationery
---| 1 # MAIL_STATIONERY_TEST
---| 41 # MAIL_STATIONERY_DEFAULT
---| 61 # MAIL_STATIONERY_GM
---| 62 # MAIL_STATIONERY_AUCTION
---| 64 # MAIL_STATIONERY_VAL
---| 65 # MAIL_STATIONERY_CHR
---| 67 # MAIL_STATIONERY_ORP

-- MailStationery
MAIL_STATIONERY_TEST = 1
MAIL_STATIONERY_DEFAULT = 41
MAIL_STATIONERY_GM = 61
MAIL_STATIONERY_AUCTION = 62
MAIL_STATIONERY_VAL = 64
MAIL_STATIONERY_CHR = 65
MAIL_STATIONERY_ORP = 67

---@alias MovementGeneratorType
---| 0 # IDLE_MOTION_TYPE
---| 1 # RANDOM_MOTION_TYPE
---| 2 # WAYPOINT_MOTION_TYPE
---| 3 # MAX_DB_MOTION_TYPE
---| 3 # ANIMAL_RANDOM_MOTION_TYPE
---| 4 # CONFUSED_MOTION_TYPE
---| 5 # CHASE_MOTION_TYPE
---| 6 # HOME_MOTION_TYPE
---| 7 # FLIGHT_MOTION_TYPE
---| 8 # POINT_MOTION_TYPE
---| 9 # FLEEING_MOTION_TYPE
---| 10 # DISTRACT_MOTION_TYPE
---| 11 # ASSISTANCE_MOTION_TYPE
---| 12 # ASSISTANCE_DISTRACT_MOTION_TYPE
---| 13 # TIMED_FLEEING_MOTION_TYPE
---| 14 # FOLLOW_MOTION_TYPE
---| 15 # ROTATE_MOTION_TYPE
---| 16 # EFFECT_MOTION_TYPE
---| 17 # NULL_MOTION_TYPE

-- MovementGeneratorType
IDLE_MOTION_TYPE = 0
RANDOM_MOTION_TYPE = 1
WAYPOINT_MOTION_TYPE = 2
MAX_DB_MOTION_TYPE = 3
ANIMAL_RANDOM_MOTION_TYPE = 3
CONFUSED_MOTION_TYPE = 4
CHASE_MOTION_TYPE = 5
HOME_MOTION_TYPE = 6
FLIGHT_MOTION_TYPE = 7
POINT_MOTION_TYPE = 8
FLEEING_MOTION_TYPE = 9
DISTRACT_MOTION_TYPE = 10
ASSISTANCE_MOTION_TYPE = 11
ASSISTANCE_DISTRACT_MOTION_TYPE = 12
TIMED_FLEEING_MOTION_TYPE = 13
FOLLOW_MOTION_TYPE = 14
ROTATE_MOTION_TYPE = 15
EFFECT_MOTION_TYPE = 16
NULL_MOTION_TYPE = 17

---@alias PacketEvents
---| 5 # PACKET_EVENT_ON_PACKET_RECEIVE
---| 6 # PACKET_EVENT_ON_PACKET_RECEIVE_UNKNOWN
---| 7 # PACKET_EVENT_ON_PACKET_SEND
---| 8 # PACKET_EVENT_COUNT

-- PacketEvents
PACKET_EVENT_ON_PACKET_RECEIVE = 5
PACKET_EVENT_ON_PACKET_RECEIVE_UNKNOWN = 6
PACKET_EVENT_ON_PACKET_SEND = 7
PACKET_EVENT_COUNT = 8

---@alias PlayerEvents
---| 1 # PLAYER_EVENT_ON_CHARACTER_CREATE
---| 2 # PLAYER_EVENT_ON_CHARACTER_DELETE
---| 3 # PLAYER_EVENT_ON_LOGIN
---| 4 # PLAYER_EVENT_ON_LOGOUT
---| 5 # PLAYER_EVENT_ON_SPELL_CAST
---| 6 # PLAYER_EVENT_ON_KILL_PLAYER
---| 7 # PLAYER_EVENT_ON_KILL_CREATURE
---| 8 # PLAYER_EVENT_ON_KILLED_BY_CREATURE
---| 9 # PLAYER_EVENT_ON_DUEL_REQUEST
---| 10 # PLAYER_EVENT_ON_DUEL_START
---| 11 # PLAYER_EVENT_ON_DUEL_END
---| 12 # PLAYER_EVENT_ON_GIVE_XP
---| 13 # PLAYER_EVENT_ON_LEVEL_CHANGE
---| 14 # PLAYER_EVENT_ON_MONEY_CHANGE
---| 15 # PLAYER_EVENT_ON_REPUTATION_CHANGE
---| 16 # PLAYER_EVENT_ON_TALENTS_CHANGE
---| 17 # PLAYER_EVENT_ON_TALENTS_RESET
---| 18 # PLAYER_EVENT_ON_CHAT
---| 19 # PLAYER_EVENT_ON_WHISPER
---| 20 # PLAYER_EVENT_ON_GROUP_CHAT
---| 21 # PLAYER_EVENT_ON_GUILD_CHAT
---| 22 # PLAYER_EVENT_ON_CHANNEL_CHAT
---| 23 # PLAYER_EVENT_ON_EMOTE
---| 24 # PLAYER_EVENT_ON_TEXT_EMOTE
---| 25 # PLAYER_EVENT_ON_SAVE
---| 26 # PLAYER_EVENT_ON_BIND_TO_INSTANCE
---| 27 # PLAYER_EVENT_ON_UPDATE_ZONE
---| 28 # PLAYER_EVENT_ON_MAP_CHANGE
---| 29 # PLAYER_EVENT_ON_EQUIP
---| 30 # PLAYER_EVENT_ON_FIRST_LOGIN
---| 31 # PLAYER_EVENT_ON_CAN_USE_ITEM
---| 32 # PLAYER_EVENT_ON_LOOT_ITEM
---| 33 # PLAYER_EVENT_ON_ENTER_COMBAT
---| 34 # PLAYER_EVENT_ON_LEAVE_COMBAT
---| 35 # PLAYER_EVENT_ON_REPOP
---| 36 # PLAYER_EVENT_ON_RESURRECT
---| 37 # PLAYER_EVENT_ON_LOOT_MONEY
---| 38 # PLAYER_EVENT_ON_QUEST_ABANDON
---| 39 # PLAYER_EVENT_ON_LEARN_TALENTS
---| 42 # PLAYER_EVENT_ON_COMMAND
---| 43 # PLAYER_EVENT_ON_PET_ADDED_TO_WORLD
---| 44 # PLAYER_EVENT_ON_LEARN_SPELL
---| 45 # PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE
---| 46 # PLAYER_EVENT_ON_FFAPVP_CHANGE
---| 47 # PLAYER_EVENT_ON_UPDATE_AREA
---| 48 # PLAYER_EVENT_ON_CAN_INIT_TRADE
---| 49 # PLAYER_EVENT_ON_CAN_SEND_MAIL
---| 50 # PLAYER_EVENT_ON_CAN_JOIN_LFG
---| 51 # PLAYER_EVENT_ON_QUEST_REWARD_ITEM
---| 52 # PLAYER_EVENT_ON_CREATE_ITEM
---| 53 # PLAYER_EVENT_ON_STORE_NEW_ITEM
---| 54 # PLAYER_EVENT_ON_COMPLETE_QUEST
---| 55 # PLAYER_EVENT_ON_CAN_GROUP_INVITE
---| 56 # PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM
---| 57 # PLAYER_EVENT_ON_BG_DESERTION

-- PlayerEvents
PLAYER_EVENT_ON_CHARACTER_CREATE = 1
PLAYER_EVENT_ON_CHARACTER_DELETE = 2
PLAYER_EVENT_ON_LOGIN = 3
PLAYER_EVENT_ON_LOGOUT = 4
PLAYER_EVENT_ON_SPELL_CAST = 5
PLAYER_EVENT_ON_KILL_PLAYER = 6
PLAYER_EVENT_ON_KILL_CREATURE = 7
PLAYER_EVENT_ON_KILLED_BY_CREATURE = 8
PLAYER_EVENT_ON_DUEL_REQUEST = 9
PLAYER_EVENT_ON_DUEL_START = 10
PLAYER_EVENT_ON_DUEL_END = 11
PLAYER_EVENT_ON_GIVE_XP = 12
PLAYER_EVENT_ON_LEVEL_CHANGE = 13
PLAYER_EVENT_ON_MONEY_CHANGE = 14
PLAYER_EVENT_ON_REPUTATION_CHANGE = 15
PLAYER_EVENT_ON_TALENTS_CHANGE = 16
PLAYER_EVENT_ON_TALENTS_RESET = 17
PLAYER_EVENT_ON_CHAT = 18
PLAYER_EVENT_ON_WHISPER = 19
PLAYER_EVENT_ON_GROUP_CHAT = 20
PLAYER_EVENT_ON_GUILD_CHAT = 21
PLAYER_EVENT_ON_CHANNEL_CHAT = 22
PLAYER_EVENT_ON_EMOTE = 23
PLAYER_EVENT_ON_TEXT_EMOTE = 24
PLAYER_EVENT_ON_SAVE = 25
PLAYER_EVENT_ON_BIND_TO_INSTANCE = 26
PLAYER_EVENT_ON_UPDATE_ZONE = 27
PLAYER_EVENT_ON_MAP_CHANGE = 28
PLAYER_EVENT_ON_EQUIP = 29
PLAYER_EVENT_ON_FIRST_LOGIN = 30
PLAYER_EVENT_ON_CAN_USE_ITEM = 31
PLAYER_EVENT_ON_LOOT_ITEM = 32
PLAYER_EVENT_ON_ENTER_COMBAT = 33
PLAYER_EVENT_ON_LEAVE_COMBAT = 34
PLAYER_EVENT_ON_REPOP = 35
PLAYER_EVENT_ON_RESURRECT = 36
PLAYER_EVENT_ON_LOOT_MONEY = 37
PLAYER_EVENT_ON_QUEST_ABANDON = 38
PLAYER_EVENT_ON_LEARN_TALENTS = 39
PLAYER_EVENT_ON_COMMAND = 42
PLAYER_EVENT_ON_PET_ADDED_TO_WORLD = 43
PLAYER_EVENT_ON_LEARN_SPELL = 44
PLAYER_EVENT_ON_ACHIEVEMENT_COMPLETE = 45
PLAYER_EVENT_ON_FFAPVP_CHANGE = 46
PLAYER_EVENT_ON_UPDATE_AREA = 47
PLAYER_EVENT_ON_CAN_INIT_TRADE = 48
PLAYER_EVENT_ON_CAN_SEND_MAIL = 49
PLAYER_EVENT_ON_CAN_JOIN_LFG = 50
PLAYER_EVENT_ON_QUEST_REWARD_ITEM = 51
PLAYER_EVENT_ON_CREATE_ITEM = 52
PLAYER_EVENT_ON_STORE_NEW_ITEM = 53
PLAYER_EVENT_ON_COMPLETE_QUEST = 54
PLAYER_EVENT_ON_CAN_GROUP_INVITE = 55
PLAYER_EVENT_ON_GROUP_ROLL_REWARD_ITEM = 56
PLAYER_EVENT_ON_BG_DESERTION = 57

---@alias Powers
---| 0 # POWER_MANA
---| 1 # POWER_RAGE
---| 2 # POWER_FOCUS
---| 3 # POWER_ENERGY
---| 4 # POWER_HAPPINESS
---| 5 # POWER_RUNE
---| 6 # POWER_RUNIC_POWER
---| 7 # MAX_POWERS
---| 127 # POWER_ALL
---| 4294967294 # POWER_HEALTH

-- Powers
POWER_MANA = 0
POWER_RAGE = 1
POWER_FOCUS = 2
POWER_ENERGY = 3
POWER_HAPPINESS = 4
POWER_RUNE = 5
POWER_RUNIC_POWER = 6
MAX_POWERS = 7
POWER_ALL = 127
POWER_HEALTH = 4294967294

---@alias QuestFlags
---| 0 # QUEST_FLAGS_NONE
---| 1 # QUEST_FLAGS_STAY_ALIVE
---| 2 # QUEST_FLAGS_PARTY_ACCEPT
---| 4 # QUEST_FLAGS_EXPLORATION
---| 8 # QUEST_FLAGS_SHARABLE
---| 16 # QUEST_FLAGS_HAS_CONDITION
---| 32 # QUEST_FLAGS_HIDE_REWARD_POI
---| 64 # QUEST_FLAGS_RAID
---| 128 # QUEST_FLAGS_TBC
---| 256 # QUEST_FLAGS_NO_MONEY_FROM_XP
---| 512 # QUEST_FLAGS_HIDDEN_REWARDS
---| 1024 # QUEST_FLAGS_TRACKING
---| 2048 # QUEST_FLAGS_DEPRECATE_REPUTATION
---| 4096 # QUEST_FLAGS_DAILY
---| 8192 # QUEST_FLAGS_FLAGS_PVP
---| 16384 # QUEST_FLAGS_UNAVAILABLE
---| 32768 # QUEST_FLAGS_WEEKLY
---| 65536 # QUEST_FLAGS_AUTOCOMPLETE
---| 131072 # QUEST_FLAGS_DISPLAY_ITEM_IN_TRACKER
---| 262144 # QUEST_FLAGS_OBJ_TEXT
---| 524288 # QUEST_FLAGS_AUTO_ACCEPT

-- QuestFlags
QUEST_FLAGS_NONE = 0
QUEST_FLAGS_STAY_ALIVE = 1
QUEST_FLAGS_PARTY_ACCEPT = 2
QUEST_FLAGS_EXPLORATION = 4
QUEST_FLAGS_SHARABLE = 8
QUEST_FLAGS_HAS_CONDITION = 16
QUEST_FLAGS_HIDE_REWARD_POI = 32
QUEST_FLAGS_RAID = 64
QUEST_FLAGS_TBC = 128
QUEST_FLAGS_NO_MONEY_FROM_XP = 256
QUEST_FLAGS_HIDDEN_REWARDS = 512
QUEST_FLAGS_TRACKING = 1024
QUEST_FLAGS_DEPRECATE_REPUTATION = 2048
QUEST_FLAGS_DAILY = 4096
QUEST_FLAGS_FLAGS_PVP = 8192
QUEST_FLAGS_UNAVAILABLE = 16384
QUEST_FLAGS_WEEKLY = 32768
QUEST_FLAGS_AUTOCOMPLETE = 65536
QUEST_FLAGS_DISPLAY_ITEM_IN_TRACKER = 131072
QUEST_FLAGS_OBJ_TEXT = 262144
QUEST_FLAGS_AUTO_ACCEPT = 524288

---@alias RemoveMethod
---| 0 # GROUP_REMOVEMETHOD_DEFAULT
---| 1 # GROUP_REMOVEMETHOD_KICK
---| 2 # GROUP_REMOVEMETHOD_LEAVE
---| 3 # GROUP_REMOVEMETHOD_KICK_LFG

-- RemoveMethod
GROUP_REMOVEMETHOD_DEFAULT = 0
GROUP_REMOVEMETHOD_KICK = 1
GROUP_REMOVEMETHOD_LEAVE = 2
GROUP_REMOVEMETHOD_KICK_LFG = 3

---@alias RollMask
---| 1 # ROLL_FLAG_TYPE_PASS
---| 2 # ROLL_FLAG_TYPE_NEED
---| 4 # ROLL_FLAG_TYPE_GREED
---| 7 # ROLL_ALL_TYPE_NO_DISENCHANT
---| 8 # ROLL_FLAG_TYPE_DISENCHANT
---| 15 # ROLL_ALL_TYPE_MASK

-- RollMask
ROLL_FLAG_TYPE_PASS = 1
ROLL_FLAG_TYPE_NEED = 2
ROLL_FLAG_TYPE_GREED = 4
ROLL_ALL_TYPE_NO_DISENCHANT = 7
ROLL_FLAG_TYPE_DISENCHANT = 8
ROLL_ALL_TYPE_MASK = 15

---@alias RollVote
---| 0 # PASS
---| 1 # NEED
---| 2 # GREED
---| 3 # DISENCHANT
---| 4 # NOT_EMITED_YET
---| 5 # NOT_VALID

-- RollVote
PASS = 0
NEED = 1
GREED = 2
DISENCHANT = 3
NOT_EMITED_YET = 4
NOT_VALID = 5

---@alias SelectAggroTarget
---| 0 # SELECT_TARGET_RANDOM
---| 1 # SELECT_TARGET_TOPAGGRO
---| 2 # SELECT_TARGET_BOTTOMAGGRO
---| 3 # SELECT_TARGET_NEAREST
---| 4 # SELECT_TARGET_FARTHEST

-- SelectAggroTarget
SELECT_TARGET_RANDOM = 0
SELECT_TARGET_TOPAGGRO = 1
SELECT_TARGET_BOTTOMAGGRO = 2
SELECT_TARGET_NEAREST = 3
SELECT_TARGET_FARTHEST = 4

---@alias ServerEvents
---| 1 # SERVER_EVENT_ON_NETWORK_START
---| 2 # SERVER_EVENT_ON_NETWORK_STOP
---| 3 # SERVER_EVENT_ON_SOCKET_OPEN
---| 4 # SERVER_EVENT_ON_SOCKET_CLOSE
---| 5 # SERVER_EVENT_ON_PACKET_RECEIVE
---| 6 # SERVER_EVENT_ON_PACKET_RECEIVE_UNKNOWN
---| 7 # SERVER_EVENT_ON_PACKET_SEND
---| 8 # WORLD_EVENT_ON_OPEN_STATE_CHANGE
---| 9 # WORLD_EVENT_ON_CONFIG_LOAD
---| 11 # WORLD_EVENT_ON_SHUTDOWN_INIT
---| 12 # WORLD_EVENT_ON_SHUTDOWN_CANCEL
---| 13 # WORLD_EVENT_ON_UPDATE
---| 14 # WORLD_EVENT_ON_STARTUP
---| 15 # WORLD_EVENT_ON_SHUTDOWN
---| 16 # ELUNA_EVENT_ON_LUA_STATE_CLOSE
---| 17 # MAP_EVENT_ON_CREATE
---| 18 # MAP_EVENT_ON_DESTROY
---| 19 # MAP_EVENT_ON_GRID_LOAD
---| 20 # MAP_EVENT_ON_GRID_UNLOAD
---| 21 # MAP_EVENT_ON_PLAYER_ENTER
---| 22 # MAP_EVENT_ON_PLAYER_LEAVE
---| 23 # MAP_EVENT_ON_UPDATE
---| 24 # TRIGGER_EVENT_ON_TRIGGER
---| 25 # WEATHER_EVENT_ON_CHANGE
---| 26 # AUCTION_EVENT_ON_ADD
---| 27 # AUCTION_EVENT_ON_REMOVE
---| 28 # AUCTION_EVENT_ON_SUCCESSFUL
---| 29 # AUCTION_EVENT_ON_EXPIRE
---| 30 # ADDON_EVENT_ON_MESSAGE
---| 31 # WORLD_EVENT_ON_DELETE_CREATURE
---| 32 # WORLD_EVENT_ON_DELETE_GAMEOBJECT
---| 33 # ELUNA_EVENT_ON_LUA_STATE_OPEN
---| 34 # GAME_EVENT_START
---| 35 # GAME_EVENT_STOP

-- ServerEvents
SERVER_EVENT_ON_NETWORK_START = 1
SERVER_EVENT_ON_NETWORK_STOP = 2
SERVER_EVENT_ON_SOCKET_OPEN = 3
SERVER_EVENT_ON_SOCKET_CLOSE = 4
SERVER_EVENT_ON_PACKET_RECEIVE = 5
SERVER_EVENT_ON_PACKET_RECEIVE_UNKNOWN = 6
SERVER_EVENT_ON_PACKET_SEND = 7
WORLD_EVENT_ON_OPEN_STATE_CHANGE = 8
WORLD_EVENT_ON_CONFIG_LOAD = 9
WORLD_EVENT_ON_SHUTDOWN_INIT = 11
WORLD_EVENT_ON_SHUTDOWN_CANCEL = 12
WORLD_EVENT_ON_UPDATE = 13
WORLD_EVENT_ON_STARTUP = 14
WORLD_EVENT_ON_SHUTDOWN = 15
ELUNA_EVENT_ON_LUA_STATE_CLOSE = 16
MAP_EVENT_ON_CREATE = 17
MAP_EVENT_ON_DESTROY = 18
MAP_EVENT_ON_GRID_LOAD = 19
MAP_EVENT_ON_GRID_UNLOAD = 20
MAP_EVENT_ON_PLAYER_ENTER = 21
MAP_EVENT_ON_PLAYER_LEAVE = 22
MAP_EVENT_ON_UPDATE = 23
TRIGGER_EVENT_ON_TRIGGER = 24
WEATHER_EVENT_ON_CHANGE = 25
AUCTION_EVENT_ON_ADD = 26
AUCTION_EVENT_ON_REMOVE = 27
AUCTION_EVENT_ON_SUCCESSFUL = 28
AUCTION_EVENT_ON_EXPIRE = 29
ADDON_EVENT_ON_MESSAGE = 30
WORLD_EVENT_ON_DELETE_CREATURE = 31
WORLD_EVENT_ON_DELETE_GAMEOBJECT = 32
ELUNA_EVENT_ON_LUA_STATE_OPEN = 33
GAME_EVENT_START = 34
GAME_EVENT_STOP = 35

---@alias SheathState
---| 0 # SHEATH_STATE_UNARMED
---| 1 # SHEATH_STATE_MELEE
---| 2 # SHEATH_STATE_RANGED

-- SheathState
SHEATH_STATE_UNARMED = 0
SHEATH_STATE_MELEE = 1
SHEATH_STATE_RANGED = 2

---@alias SpellSchoolMask
---| 0 # SPELL_SCHOOL_MASK_NONE
---| 1 # SPELL_SCHOOL_MASK_NORMAL
---| 2 # SPELL_SCHOOL_MASK_HOLY
---| 4 # SPELL_SCHOOL_MASK_FIRE
---| 8 # SPELL_SCHOOL_MASK_NATURE
---| 16 # SPELL_SCHOOL_MASK_FROST
---| 32 # SPELL_SCHOOL_MASK_SHADOW
---| 64 # SPELL_SCHOOL_MASK_ARCANE

-- SpellSchoolMask
SPELL_SCHOOL_MASK_NONE = 0
SPELL_SCHOOL_MASK_NORMAL = 1
SPELL_SCHOOL_MASK_HOLY = 2
SPELL_SCHOOL_MASK_FIRE = 4
SPELL_SCHOOL_MASK_NATURE = 8
SPELL_SCHOOL_MASK_FROST = 16
SPELL_SCHOOL_MASK_SHADOW = 32
SPELL_SCHOOL_MASK_ARCANE = 64

---@alias SpellSchools
---| 0 # SPELL_SCHOOL_NORMAL
---| 1 # SPELL_SCHOOL_HOLY
---| 2 # SPELL_SCHOOL_FIRE
---| 3 # SPELL_SCHOOL_NATURE
---| 4 # SPELL_SCHOOL_FROST
---| 5 # SPELL_SCHOOL_SHADOW
---| 6 # SPELL_SCHOOL_ARCANE
---| 7 # MAX_SPELL_SCHOOL

-- SpellSchools
SPELL_SCHOOL_NORMAL = 0
SPELL_SCHOOL_HOLY = 1
SPELL_SCHOOL_FIRE = 2
SPELL_SCHOOL_NATURE = 3
SPELL_SCHOOL_FROST = 4
SPELL_SCHOOL_SHADOW = 5
SPELL_SCHOOL_ARCANE = 6
MAX_SPELL_SCHOOL = 7

---@alias TeamId
---| 0 # TEAM_ALLIANCE
---| 1 # TEAM_HORDE
---| 2 # TEAM_NEUTRAL

-- TeamId
TEAM_ALLIANCE = 0
TEAM_HORDE = 1
TEAM_NEUTRAL = 2

---@alias TempSummonType
---| 1 # TEMPSUMMON_TIMED_OR_DEAD_DESPAWN
---| 2 # TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN
---| 3 # TEMPSUMMON_TIMED_DESPAWN
---| 4 # TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT
---| 5 # TEMPSUMMON_CORPSE_DESPAWN
---| 6 # TEMPSUMMON_CORPSE_TIMED_DESPAWN
---| 7 # TEMPSUMMON_DEAD_DESPAWN
---| 8 # TEMPSUMMON_MANUAL_DESPAWN
---| 9 # TEMPSUMMON_TIMED_OOC_OR_CORPSE_DESPAWN
---| 10 # TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN

-- TempSummonType
TEMPSUMMON_TIMED_OR_DEAD_DESPAWN = 1
TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN = 2
TEMPSUMMON_TIMED_DESPAWN = 3
TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT = 4
TEMPSUMMON_CORPSE_DESPAWN = 5
TEMPSUMMON_CORPSE_TIMED_DESPAWN = 6
TEMPSUMMON_DEAD_DESPAWN = 7
TEMPSUMMON_MANUAL_DESPAWN = 8
TEMPSUMMON_TIMED_OOC_OR_CORPSE_DESPAWN = 9
TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN = 10

---@alias TypeID
---| 0 # TYPEID_OBJECT
---| 1 # TYPEID_ITEM
---| 2 # TYPEID_CONTAINER
---| 3 # TYPEID_UNIT
---| 4 # TYPEID_PLAYER
---| 5 # TYPEID_GAMEOBJECT
---| 6 # TYPEID_DYNAMICOBJECT
---| 7 # TYPEID_CORPSE

-- TypeID
TYPEID_OBJECT = 0
TYPEID_ITEM = 1
TYPEID_CONTAINER = 2
TYPEID_UNIT = 3
TYPEID_PLAYER = 4
TYPEID_GAMEOBJECT = 5
TYPEID_DYNAMICOBJECT = 6
TYPEID_CORPSE = 7

---@alias UnitMoveType
---| 0 # MOVE_WALK
---| 1 # MOVE_RUN
---| 2 # MOVE_RUN_BACK
---| 3 # MOVE_SWIM
---| 4 # MOVE_SWIM_BACK
---| 5 # MOVE_TURN_RATE
---| 6 # MOVE_FLIGHT
---| 7 # MOVE_FLIGHT_BACK
---| 8 # MOVE_PITCH_RATE

-- UnitMoveType
MOVE_WALK = 0
MOVE_RUN = 1
MOVE_RUN_BACK = 2
MOVE_SWIM = 3
MOVE_SWIM_BACK = 4
MOVE_TURN_RATE = 5
MOVE_FLIGHT = 6
MOVE_FLIGHT_BACK = 7
MOVE_PITCH_RATE = 8

---@alias WeatherType
---| 0 # WEATHER_TYPE_FINE
---| 1 # WEATHER_TYPE_RAIN
---| 2 # WEATHER_TYPE_SNOW
---| 3 # WEATHER_TYPE_STORM
---| 86 # WEATHER_TYPE_THUNDERS
---| 90 # WEATHER_TYPE_BLACKRAIN

-- WeatherType
WEATHER_TYPE_FINE = 0
WEATHER_TYPE_RAIN = 1
WEATHER_TYPE_SNOW = 2
WEATHER_TYPE_STORM = 3
WEATHER_TYPE_THUNDERS = 86
WEATHER_TYPE_BLACKRAIN = 90

